### ISSUE TITLE
turn off CONFIG: LOGGING ENABLED GLOBALLY 

### ISSUE THREAD

**Issue by lookfirst** [lwhiteley/AngularLogExtender#34]
I'd like the option to not output that line.

**Comment by ferronrsmith** [comment]
```javascript
app.config(['logExProvider', function(logExProvider) {
    var enabledLogging=true, enableQuietly=true;
    logExProvider.enableLogging(enabledLogging, enableQuietly);
}]);
```

**Comment by ferronrsmith** [comment]
@lwhiteley you can push the latest version of the log extender to bower, thanks!

**Comment by lwhiteley** [comment]
@ferronrsmith bower uses the git tags and should use 0.0.10 by default as the latest version now. 
i also just confirmed by downloading it

**Comment by ferronrsmith** [comment]
ok great awesome, thanks!

On Sun, Apr 12, 2015 at 9:52 PM, Layton Whiteley <notifications@github.com>
wrote:

> @ferronrsmith <https://github.com/ferronrsmith> bower uses the git tags
> and should use 0.0.10 by default as the latest version now.
> i also just confirmed by downloading it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lwhiteley/AngularLogExtender/issues/34#issuecomment-92168160>
> .
>



-- 
"*Give me a place to stand* on, *and I will move the Earth*."

Ferron Hanse
