### ISSUE TITLE
Testing Services with AngularLogExtender

### ISSUE THREAD

**Issue by gmaggess** [lwhiteley/AngularLogExtender#36]
Hello,

I'm an Angular newbie and I'm trying to test a service that uses the log extender. It currently fails when the test hits $log.getIntance(). Does anyone have an example on how to inject / mock log extender on Angular tests? 

Any help is appreciated.

Cheers,
George

**Comment by lwhiteley** [comment]
Hey can you post a code sample/gist of the service and the test. that would be helpful

Thanks

**Comment by gmaggess** [comment]
Sure. My bad. That's my test:

define(['angular', 'angular-mocks', 'app'], function(angular, mocks, app) {
   'use strict';

   describe('Service: myApi', function() {
      // instantiate service
      var myApi, log;

      // load the service's module
      beforeEach(function() {
         module('App.services.MyApi');
         inject(function(_$log_, _MyApi_) {
            log = _$log_;
            log.getInstance = jasmine.createSpy('getInstance');
            myApi = _MyApi_;
         });
      });

      it('should do initialize', function() {
         myApi.init('127.0.0.1').then(function(session) {
            expect(session).not.toBe(null);
         }, function(error) {
            expect(error).toBeUndefined()
         });
      });

   });
});

Code fails inside myApi, right exactly where $log.getInstance is invoked.

Hope this helps.

**Comment by ferronrsmith** [comment]
Just an FYI. If you're including `angular-mocks` in your tests (which you should), then it will override the implementation of $log with a mocked version. You would need to override the provider and extended the  $log with the `getInstance` spy.


```javascript
describe('$log', function() {
  var $window, logger, log, warn, info, error, debug;

  beforeEach(module(function($provide) {
    $window = {navigator: {}, document: {}};
    logger = '';
    log = function() { logger+= 'log;'; };
    warn = function() { logger+= 'warn;'; };
    info = function() { logger+= 'info;'; };
    error = function() { logger+= 'error;'; };
    debug = function() { logger+= 'debug;'; };

    $provide.provider('$log', $LogProvider);
    $provide.value('$window', $window);
  }));

  it('should use console if present', inject(
    function() {
      $window.console = {log: log,
                         warn: warn,
                         info: info,
                         error: error,
                         debug: debug};
    },
    function($log) {
      $log.log();
      $log.warn();
      $log.info();
      $log.error();
      $log.debug();
      expect(logger).toEqual('log;warn;info;error;debug;');
    }
  ));
```

**Comment by gmaggess** [comment]
Hi ferronrsmith,

Thanks for your answer. So, that's what I tried to do, but still no success:

   describe('Service: myApi', function() {
      // instantiate service
      var myApi, log;

      // load the service's module
      beforeEach(function() {
         module('myApp.services.MyApi', function($provide, $logProvider) {
            $provide.value('$log', $logProvider);
         });
         inject(function(_MyApi_) {
            myApi = _MyApi_;
         });
      });

      it('should do initialize', function() {
         inject(function($log) {
            $log.getInstance = jasmine.createSpy('getInstance');
            myApi.init('127.0.0.1).then(function(session) {
               expect(session).not.toBe(null);
            }, function(error) {
               expect(error).toBeUndefined()
            });
         });
      });
   });

myApi.init() still fails due to a missing getInstance method on $log. Plus the $log in "$log.getInstance = jasmine.createSpy('getInstance');" does not have all debug, log, warn, etc methods.

Any help is appreciated.

Cheers,
George

**Comment by ferronrsmith** [comment]
When u add a spy to getInstance, does the spy actually gets called ?
