### ISSUE TITLE
color support for more than one argument

### ISSUE THREAD

**Issue by rweng** [lwhiteley/AngularLogExtender#37]
Hi,

color support works fine when using

    $log.warn("test") // printed correctly in orange

however, with multiple parameters it doesn't work:

    $log.warn("test", "test") // printed incorrectly in black

All the best,
Robin

**Comment by ferronrsmith** [comment]
Second field is usually reserved for color overrides. 

 $log.log('%c Oh my heavens! ', 'background: #222; color: #bada55');

**Comment by rweng** [comment]
arg. I thought since you have examples like `$log = $log.getInstance(...)`, that the API would actually stay the same as in normal angular `$log`, which you do use like `$log.log(p1, p2, p3, ...)`.

Too bad, this is actually a show-stopper for us, since we are not going to use a custom API. I would expect the styling to be overwritten as it is used on the provider, with `$log.setLogMethodColor`.

**Comment by ferronrsmith** [comment]
I get what your saying, but it's not really an limitation of the library per say, but the browsers. If you take a look at the documentation for coloring in chrome/ff the second parameter always defines color

```javascript
console.log("%cThis will be formatted with large, blue text", "color: blue; font-size: x-large");
```

https://developer.chrome.com/devtools/docs/console#styling-console-output-with-css.
