### ISSUE TITLE
ability to config use of Templating Engine for all app

### ISSUE THREAD

**Issue by innovaterz** [lwhiteley/AngularLogExtender#44]
Hi,
Is there a way to config use of Templating Engine for all app instead of declare it in each component all over again?
Thanks

**Comment by ferronrsmith** [comment]
you want a mechanism that will allow you to plugin pre-defined values that then would be replaced on the fly right ? Just so I get you clearly....


Something similar to [log filters](https://github.com/lwhiteley/AngularLogExtender/wiki/12.-Filter-sensitive-information-from-logs), but for the templating engine ?

**Comment by lwhiteley** [comment]
I think he means instead of  the task of having the task of enabling the template engine in each component (controllers, services, etc...), why not have a global config to set `useTemplateEngine` to true. 

you can confirm @innovaterz

**Comment by ferronrsmith** [comment]
Which is exactly like [log filters](https://github.com/lwhiteley/AngularLogExtender/wiki/12.-Filter-sensitive-information-from-logs).

**Comment by ferronrsmith** [comment]
```javascript

app.config(['logExProvider', function(logExProvider) {
    // this will extend the default configurations and enable the filtering of sensitive
    // information for the specified keys.
    logExProvider.configureTemplatingEngine({
      map:{
          example : 6,
          template : "what's for dinner ?",
          transpose : "should I come by at {example}" // inner tranposition
      }
    });
}]);


$log.log('Tom said :  {transpose}');
// >> Dec-08-2013-1:00:47PM >>  CONFIG: LOGGING ENABLED GLOBALLY
// >> Dec-08-2013-1:00:47PM::CoreController >>  Tom said : should I come by at 6

```

This was how I envisioned it. Not sure what you think @lwhiteley

**Comment by lwhiteley** [comment]
From what I'm seeing there it looks like a good feature, however lets confirm what @innovaterz issue is.

We can decide if what you have there is a separate issue or if it will be done as a part of this issue and further flesh out the logic

**Comment by innovaterz** [comment]
Hi, thanks for your replies. I'm thinking more with @lwhiteley direction, to enable global config for  template engine use, defining  and controlling it from one place for all app. Its really nice to have, otherwise just have to explicitly declaring it for each component. 
Anyway LogEx is great feature!

**Comment by ferronrsmith** [comment]
@innovaterz thanks for confirmations. @lwhiteley you want to take this ?

**Comment by lwhiteley** [comment]
Yea I could take it

On Wed, Jun 3, 2015, 10:54 AM Ferron H <notifications@github.com> wrote:

> @innovaterz <https://github.com/innovaterz> thanks for confirmations.
> @lwhiteley <https://github.com/lwhiteley> you want to take this ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lwhiteley/AngularLogExtender/issues/44#issuecomment-108468242>
> .
>
-- 
_______________
Regards
Layton Whiteley

**Comment by ferronrsmith** [comment]
close by : https://github.com/lwhiteley/AngularLogExtender/commit/81ca906bd38129258d2036e9b3abee54360f5bd0
