### ISSUE TITLE
configureLogFilters appears to be modifying more than log entries

### ISSUE THREAD

**Issue by eppineda** [lwhiteley/AngularLogExtender#46]
I'm still trying to get to the bottom of it, but it appears calls to `logEx.configureLogFilters` is modifying more than log entries. I discovered it was, for reasons I don't understand yet, also modifying the strings for my http requests in other, unrelated parts of the application. (Subsequently, the modified strings were being rejected by the REST service my application uses.)

If I comment out the calls to `logEx.configureLogFilters`, the REST service works because the http requests remain intact.

gist: https://gist.github.com/eppineda/8d37faf5e40cb3d89e6a947ecd43abb6

![filters](https://cloud.githubusercontent.com/assets/6559491/18690913/bef931be-7f5e-11e6-9d7f-fb7d732fe65a.png)

(btw, _thank you_ for your fine work on this! I hope to contribute...)

**Comment by ferronrsmith** [comment]
@eppineda made a patch `dev-release` [ 0.0.12-1+sha.f3cb067](https://github.com/lwhiteley/AngularLogExtender/releases/tag/0.0.12-1%2Bsha.f3cb067). Test and let me know if your issue has been resovled.

**Comment by eppineda** [comment]
all better now! thanks @ferronrsmith

**Comment by ferronrsmith** [comment]
you're welcome
